nextcloud/sharepoint

.travis.yml
CHANGELOG.md
appinfo/info.xml
tests/phpunit.xml

* [missing/unthemed icon for external storages](https://github.com/nextcloud/server/issues/7934)

Add Nextcloud 13 compatibility

---

.travis.yml
appinfo/info.xml

refs https://github.com/nextcloud/server/issues/11065

adjust to stable14

---

Makefile
appinfo/info.xml

version bump for a maintenance release

bump to 1.3.1

---

README.md
composer.json
composer.lock
lib/Client.php
lib/ContextsFactory.php
lib/Storage/Storage.php
tests/Unit/ClientTest.php
tests/Unit/StorageTest.php

deprecates #37 (fixes and SP 365 support)

mtimes, caching, 365 support

---

tests/Unit/StorageTest.php

Signed-off-by: Arthur Schiwon <blizzz@arthur-schiwon.de>

fix silently (18+) failing unit tests

---

lib/Client.php
tests/Unit/ClientTest.php
tests/Unit/StorageTest.php

Do not depend on sharepoint error messages

---

appinfo/info.xml

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

l10n: Remove comma

---

phpunit.integration.xml
phpunit.xml
tests/phpunit.xml

Update master php testing versions

---

lib/Client.php

addCustomHeader not working
ensureHeader instead
Signed-off-by: newmaka50 <43097142+newmaka50@users.noreply.github.com>

fix stream upload headers

---

lib/Client.php

[stable25] fix stream upload headers

---

lib/Client.php

backport of https://github.com/nextcloud/sharepoint/pull/158

[stable24] fix stream upload headers

---

composer.json
composer.lock
lib/Client.php
lib/ClientFactory.php
lib/Storage/Storage.php
tests/Unit/ClientTest.php
tests/Unit/StorageTest.php

- bumping phpSPO from 2.4.5 to 3.0.1 for better PHP 8 compatibility and file handling fixes
- our own compat and file handling fixes

improve PHP 8.x compatibility and special char fixes

---

composer.json
composer.lock
lib/Client.php
lib/ClientFactory.php
lib/Storage/Storage.php
tests/Unit/ClientTest.php
tests/Unit/StorageTest.php

[stable25] improve PHP 8.x compatibility and special char fixes

---

composer.json
composer.lock
lib/Client.php
lib/ClientFactory.php
lib/Storage/Storage.php
tests/Unit/ClientTest.php
tests/Unit/StorageTest.php

backport of https://github.com/nextcloud/sharepoint/pull/154

[stable24] improve PHP 8.x compatibility and special char fixes

---

.github/workflows/phpunit-mysql.yml
appinfo/info.xml

chore: Add Nextcloud 27 support on master

---

.github/workflows/integration.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml

chore(CI): Adjust testing matrix for Nextcloud 26 on stable26

---

.github/workflows/integration.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml

chore(CI): Adjust testing matrix for Nextcloud 27 on stable27

---

.github/workflows/integration.yml
.github/workflows/phpunit-mariadb.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml

chore(CI): Adjust testing matrix for Nextcloud 28 on stable28

---

appinfo/info.xml

feat(deps): Add Nextcloud 30 support on master

---

.github/workflows/integration.yml

chore(CI): Adjust testing matrix for Nextcloud 29 on stable29

---

.github/workflows/appstore-build-publish.yml
.github/workflows/integration.yml
.github/workflows/lint-php-cs.yml
.github/workflows/lint-php.yml
.github/workflows/phpunit-mariadb.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
.github/workflows/pr-feedback.yml

chore(CI): Adjust testing matrix for Nextcloud 30 on stable30

---

.github/workflows/appstore-build-publish.yml
.github/workflows/integration.yml
.github/workflows/lint-php-cs.yml
.github/workflows/phpunit-mariadb.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
.github/workflows/pr-feedback.yml
.github/workflows/psalm.yml
appinfo/info.xml
composer.json
composer.lock
lib/Client.php
lib/Listener/ExternalStoragesRegistrationListener.php
lib/Storage/Storage.php
psalm.xml
tests/stub.phpstub

feat(deps): Add Nextcloud 31 support on master

---

lib/Storage/Storage.php

Signed-off-by: Julius Knorr <jus@bitgrid.net>

debug: Write exception to log

---

.github/dependabot.yml
appinfo/info.xml

feat(deps): Add Nextcloud 32 support on master

---

.github/workflows/integration.yml
composer.json
composer.lock

chore(CI): Adjust testing matrix for Nextcloud 31 on stable31
